### ISSUE TITLE
[3] Investigate BigQuery Golang client

### ISSUE THREAD

**Issue by debnil** [stellar/project-viewer#3]
**What**
We need to determine the best Golang client for BigQuery. We don't need anything too special - ideally something light, simple, and frequently maintained.

**Why**
This will allow us to natively query BigQuery, within the backend codebase, without needing to interface with code in a different language or in a different part of the repo.

**Comment by Isaiah-Turner** [comment]
I used [this library](https://godoc.org/cloud.google.com/go/bigquery) for the MVP. It's easy to query tables and datasets in BigQuery. Authentication is also easy given a authentication key file.
